name: github-stars-reminder-manual
on: repository_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: yarn
      - name: Start
        run: npm run start
        env:
          GH_TOKEN: "${{secrets.GH_TOKEN}}"
          GH_USER: "${{secrets.GH_USER}}"
          MAIL_USER: "${{secrets.MAIL_USER}}"
          MAIL_PASS: "${{secrets.MAIL_PASS}}"
          MAIL_HOST: "${{secrets.MAIL_HOST}}"
          MAIL_PORT: ${{secrets.MAIL_PORT}}
          MAIL_FROM: "${{secrets.MAIL_FROM}}"
          MAIL_TO: "${{secrets.MAIL_TO}}"
          TOP_NUMBER: ${{secrets.TOP_NUMBER}}
          DATA_REPO: "${{secrets.DATA_REPO}}"
      - name: Publish page
        run: |
          cd results
          git init
          git config user.name "Molunerfinn"
          git config user.email "marksz@teamsz.xyz"
          git add index.html
          git commit -m "GitHub actions build pages"
          git push --force --quiet "https://${GH_TOKEN}@github.com/Molunerfinn/github-stars-reminder.git" master:gh-pages
        env:
          GH_TOKEN: "${{secrets.GH_TOKEN}}"
